server:
  port: 8761

spring:
  application:
    name: discovery-server

eureka:
  client:
    register-with-eureka: false  # Do not register the server with itself
    fetch-registry: false       # Do not fetch registry (it's the server)
  server:
    wait-time-in-ms-when-sync-empty: 0  # Serve immediately without waiting for peer sync
